### Login admin
POST http://localhost:5000/api/Auth/login
Content-Type: application/json

{
  "email": "admin@calendify.local",
  "password": "admin123"
}
### Login employee
POST http://localhost:5000/api/Auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "employee123"
}

### login user
POST http://localhost:5000/api/Auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "admin123"
}

### Check Session
GET http://localhost:5000/api/Auth/session

### Register
POST http://localhost:5000/api/Auth/Register
Content-Type: application/json

{
  "name": "New User",
  "email": "test1@test.com",
  "password": "Test123!"
}

### Logout
POST http://localhost:5000/api/Auth/logout

### Delete Employee
DELETE http://localhost:5000/api/Auth/Employee/4
